# YAJL_FOUND
# YAJL_INCLUDE_DIRS
# YAJL_LIBRARIES
include(LibFindMacros)

find_path(YAJL_INCLUDE_DIR NAMES yajl.h)
find_library(YAJL_LIBRARY NAMES yajl)

set(YAJL_PROCESS_INCLUDES YAJL_INCLUDE_DIR)
set(YAJL_PROCESS_LIBS YAJL_LIBRARY)
libfind_process(YAJL)
